Allow customer app data to be any
pliancy/api-sdk pull request #3
Opened 2021-06-25 19:44 UTC by santese

2021-06-25 19:46 UTC, santese commented
Needed to switch the CustomerApp data to any to allow for all the apps different properties

2021-06-25 20:49 UTC, noticeeverything requested changes

2021-06-25 20:49 UTC, noticeeverything commented on src/lib/types/api/apps.interfaces.ts
>  import { LdapApp } from '../ldap/ldap.interfaces'
Unused imports should be removed. VSCode probably has a setting to do that on save.

2021-06-25 20:49 UTC, noticeeverything commented on src/lib/types/api/apps.interfaces.ts
> -
Are the possibilities too many to be able to write a discreet type?

2021-06-25 20:53 UTC, santese commented on src/lib/types/api/apps.interfaces.ts
>  import { LdapApp } from '../ldap/ldap.interfaces'
That one is still used here:
https://github.com/pliancy/api-sdk/blob/b46581e01f15b67573509732ff1bfec98be72f9b/src/lib/types/api/apps.interfaces.ts#L10

2021-06-25 20:54 UTC, santese commented on src/lib/types/api/apps.interfaces.ts
> -
Yeah i think so, every app has different properties for data

2021-06-25 21:37 UTC, CalebAlbers commented on src/lib/types/api/apps.interfaces.ts
> -
Apps can have arbitrary data, but we can still export a specific type for the O365 app data (since it has a specific structure). It may be preferable for types like that to exist inside the target application referencing the, though, since it is not API-specific. What do you guys think?

2021-06-28 13:37 UTC, noticeeverything commented on src/lib/types/api/apps.interfaces.ts
> -
Yeah, ideally each lib should export its own types. The downside means another dependency here (and elsewhere) just for types, though. Maybe we should publish an `@types/pliancy` package? 

As for this PR, are there at least some data properties that all the apps have in common? `id`, for instance, and hopefully others? Then at least we can have something like:

```
export interface AppData {
    id: string
    [index: string]: any
}
```

2021-06-28 13:38 UTC, noticeeverything commented on src/lib/types/api/apps.interfaces.ts
>  import { LdapApp } from '../ldap/ldap.interfaces'
Oops, I forgot I wasn't looking at the whole file 🤦

2021-07-01 21:17 UTC, CalebAlbers approved these changes

2021-07-02 06:45 UTC, santese commented on src/lib/types/api/apps.interfaces.ts
> -
@noticeeverything there doesn't seem to be any common properties in app.data, the id is common in app.appId

2021-07-02 19:53 UTC, merged